export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as Testimoniales } from './Testimoniales'
export { default as Cta } from './Cta'
export { default as Footer } from './Footer'